import Head from 'next/head'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon/favicon.ico" />
        <link rel="apple-touch-icon" href="favicon/logo192.png" />
        <link rel="manifest" href="favicon/manifest.json" />
      </Head>

      <Hero />

    </div>
  )
}
