import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
      </Head>

      <h1 className="text-4xl font-bold underline">
        Hello world!
      </h1>

    </div>
  )
}
